#!/bin/bash
#sudo chmod +x transferscript

echo Transfer webSrc /var/www/

sudo cp -r  webSrc/* /var/www/

echo Transfer cgiScripts to /usr/lib/cgi-bin/

sudo cp -r  lowLevelSrc/cgiScripts/* /usr/lib/cgi-bin/
sudo chmod  +x /usr/lib/cgi-bin/*

echo Transfer hardware.conf to /etc/lirc
sudo cp -f lowLevelSrc/lirc/hardware.conf /etc/lirc/

echo Create lircd.conf and transfer to /etc/lirc/
sudo cp -f lowLevelSrc/lirc/lircd.conf /etc/lirc/
